# Generated by Django 5.1 on 2024-09-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litreview_app', '0002_review_author_review_date_created_review_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='photo',
        ),
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
